package space

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// vectors mirrors testdata/vectors.json, generated by running the reference
// implementation (@atproto/space at 5b95b2f2) with fixed keys. See
// testdata/SOURCE.
type vectors struct {
	Now    int64 `json:"now"`
	LtHash []struct {
		Ops    [][2]string `json:"ops"`
		State  string      `json:"state"`
		Digest string      `json:"digest"`
		Empty  bool        `json:"empty"`
	} `json:"lthash"`
	Commits []struct {
		Ctx     CommitCtx `json:"ctx"`
		DidKey  string    `json:"didKey"`
		Records []struct {
			Collection string `json:"collection"`
			Rkey       string `json:"rkey"`
			Cid        string `json:"cid"`
			Element    string `json:"element"`
		} `json:"records"`
		Ikm      string `json:"ikm"`
		CtxBytes string `json:"ctxBytes"`
		Hash     string `json:"hash"`
		Mac      string `json:"mac"`
		Sig      string `json:"sig"`
	} `json:"commits"`
	HTTPSig []struct {
		KeyDid        string            `json:"keyDid"`
		CredentialKey *string           `json:"credentialKey"`
		Headers       map[string]string `json:"headers"`
	} `json:"httpsig"`
	Tokens []struct {
		Type       string          `json:"type"`
		JWT        string          `json:"jwt"`
		SigningKey string          `json:"signingKey"`
		Opts       json.RawMessage `json:"opts"`
	} `json:"tokens"`
}

func loadVectors(t *testing.T) vectors {
	t.Helper()
	b, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v vectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
